[package]
name = "tarantool-test"
version = "0.1.0"
authors = ["Chertov Maxim <chertovmv@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
path = "./src/lib.rs"

[dependencies]
anyhow = "1"
log = "0.4"
chrono = "0.4"
chrono-humanize = "0.2.1"

once_cell = "1.8.0"
parking_lot = "0.11"
